data1 = load '/home/ruchit/ebd/data_input_pig/covid-data_id.csv' using PigStorage(',') AS (case_id,
iso_code ,
continent ,
country ,
case_date,
total_cases ,
new_cases ,
new_cases_smoothed ,
total_deaths ,
new_deaths ,
new_deaths_smoothed , 
total_cases_per_million ,
new_cases_per_million ,
new_cases_smoothed_per_million ,
total_deaths_per_million ,
new_deaths_per_million ,
new_deaths_smoothed_per_million ,
reproduction_rate ,
icu_patients ,
icu_patients_per_million ,
hosp_patients ,
hosp_patients_per_million ,
weekly_icu_admissions ,
weekly_icu_admissions_per_million ,
weekly_hosp_admissions ,
weekly_hosp_admissions_per_million ,
total_tests ,
new_tests ,
total_tests_per_thousand ,
new_tests_per_thousand , 
new_tests_smoothed ,
 new_tests_smoothed_per_thousand ,
 positive_rate ,
 tests_per_case ,
 tests_units ,
 ency_index ,
 population ,
 population_density ,
 median_age , 
 aged_65_older ,
 aged_70_older ,
 gdp_per_capita ,
 extreme_poverty ,
 cardiovasc_death_rate ,
 diabetes_prevalence ,
 female_smokers ,
 male_smokers ,
 handwashing_facilities ,
 hospital_beds_per_thousand ,
 life_expectancy ,
 human_development_index );

data = STREAM data1 THROUGH `tail -n +2` AS (case_id,
iso_code ,
continent ,
country ,
case_date,
total_cases ,
new_cases ,
new_cases_smoothed ,
total_deaths ,
new_deaths ,
new_deaths_smoothed , 
total_cases_per_million ,
new_cases_per_million ,
new_cases_smoothed_per_million ,
total_deaths_per_million ,
new_deaths_per_million ,
new_deaths_smoothed_per_million ,
reproduction_rate ,
icu_patients ,
icu_patients_per_million ,
hosp_patients ,
hosp_patients_per_million ,
weekly_icu_admissions ,
weekly_icu_admissions_per_million ,
weekly_hosp_admissions ,
weekly_hosp_admissions_per_million ,
total_tests ,
new_tests ,
total_tests_per_thousand ,
new_tests_per_thousand , 
new_tests_smoothed ,
 new_tests_smoothed_per_thousand ,
 positive_rate ,
 tests_per_case ,
 tests_units ,
 ency_index ,
 population ,
 population_density ,
 median_age , 
 aged_65_older ,
 aged_70_older ,
 gdp_per_capita ,
 extreme_poverty ,
 cardiovasc_death_rate ,
 diabetes_prevalence ,
 female_smokers ,
 male_smokers ,
 handwashing_facilities ,
 hospital_beds_per_thousand ,
 life_expectancy ,
 human_development_index );

daily = GROUP data by case_date;

daily_cases = FOREACH daily GENERATE group as case_date, SUM(data.new_cases) as sum;

order_by_data = ORDER daily_cases BY sum DESC;

store order_by_data INTO '/home/ruchit/ebd/pig_output/case_per_day';